Add flag for release candidates gem
NREL/openstudio-gems pull request #85
Opened 2024-05-02 01:35 UTC by wenyikuang

Tested with:
- no environment variable, the Gemfile will install all packages from github
- set envrionment with `export RC_RELEASE=TRUE` the Gemfile will install `openstudio-standards` from rubygem.org
- set environment to `export FINAL_PACKAGE=TRUE` the Gemfile will try to install the gem packages from rubgem.org

WHY:
If we use Gemfile to fetch the gem from github, it will fetch all codebase even if we points to `ref:`. In most of the gems it's fine but openstudio-standards' release is only ~500 MB but the code base is ~5GB.
Which cause the issue in Openstudio-server.

2024-05-02 02:58 UTC, wenyikuang commented
After this merge and build I will:
- Update the CMakelist in OS-core
- Re-build the docker image make sure the size is around ~2G

2024-05-06 19:33 UTC, jmarrec commented on .github/workflows/build.yml
> +        & cat ..\os-gems-deps\conanbuild.ps1
This is wrong.

```suggestion
        cat ..\os-gems-deps\conanbuild.ps1
```

2024-05-06 19:41 UTC, jmarrec commented
I don't follow why this is needed. What issue is openstudio-server having?

2024-05-06 19:43 UTC, jmarrec requested changes
If there is a release candidate gem on rubygems, just comment out the `git: ` attribute in the normal section

https://rubygems.org/gems/openstudio-standards has 0.6.0-rc2 so all good

THere is no point adding another env var and this complexity.

I suggest just deleting the PR... and use #87

2024-05-06 19:47 UTC, brianlball commented
> I don't follow why this is needed. What issue is openstudio-server having?

The 5GB size is crashing CI; disk out of space

2024-05-06 20:14 UTC, closed without merging